[versions]
# libraries
junit = "4.13.2"

# plugins
changelog = "2.5.0"
kotlin = "2.2.21"
intelliJPlatform = "2.10.5"
kover = "0.9.4"
ktorVersion = "3.3.3"
qodana = "2025.2.3"
kotlinxSerialization = "1.9.0"
freeMarker = "2.3.34"
detekt = "1.23.8"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ktor-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktorVersion" }
ktor-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktorVersion" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
freemarker = { group = "org.freemarker", name = "freemarker", version.ref = "freeMarker" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
